### ISSUE TITLE
Some Spanish references don't match with the ACNH original translation

### ISSUE THREAD

**Issue by Malu-RO** [jjlmoya/diy-nook#11]
Hi, 

I have reviewed the references that currently appear in the app and keeping in mind the original translation of the ACNH the name of these items doesn't match. These issues were detected with the app version 0.1.6 

Below, you can find the current name and the correct name (according to the ACNH game)

Current Name | Suggested Name
------------ | -------------
Microbiblioteca | Punto intercambio de libros
Top Pera | Vestido Pera
Pared leña | Pared leñera
Armadura | Armadura de hierro
Mesa universidad | Mesa camarera universidad
Armadura dorada | Armadura de oro
Cadena cereza | Altavoz cereza
Corona de frutas | Corona frutal
Nave tripulada | Modulo espacial tripulado
Jarrón con flores cerezo | Jarrón con flores de cerezo
Lámpara de Jacinto | Lámpara Jacinto
Guirnalda violeta | Guirnalda viola

These translation has been collected using my personal copy of the ACNH game. I can attach files to confirm the suggested names.

Let me know if you need more information about this.

Best!

**Comment by jjlmoya** [comment]
Thanks,

Fixed: https://github.com/jjlmoya/diy-nook/commit/0c16d1f7382f377c9c74733df9fa40d367e49023
Uploading app included in version: 0.1.8
